apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-ingress
  labels:
    name: shopping-ingress
spec:
  rules:
  - host: api.hypertheory-class.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: shopping-api-service
            port: 
              number: 80
