apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-api
spec:
  selector:
    matchLabels:
      app: oncall-api
  template:
    metadata:
      labels:
        app: oncall-api
    spec:
      containers:
      - name: oncall-api
        image: oncalldeveloperapi:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
