apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
spec:
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
        resources:
          limits:
            memory: "1Gi"
           
        ports:
        - containerPort: 1433
        env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: "SA_PASSWORD"
            value: "TokyoJoe138!"
